export const ROUTE_URL = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGET_PASSWORD: "/forget-password",
  UNDEFINED: "*",
  ABOUT: "/about-us",
  CONTACT: "/contact",
  GALLERY: "/gallery",
  CAREERS: "/careers",
  SERVICE: "/Service",
  LEARN_MORE: "/learn-more/:category",
  LEARN_MORE_ABOUT_CAREER: "/careers/:category",
  WHO_WE_ARE: "/who-we-are",
  NOT_ALLOWED: "/not-allowed",
  PRIVACY_POLICY: "/privacy-policy",
  TERMS_AND_CONDITIONS: "/terms",
  COOKIE_POLICY: "/cookie-policy",
  SCHEDULE_MEETING: "/schedule-meeting",
};
